### ISSUE TITLE
Write tests to verify line endings

### ISSUE THREAD

**Issue by adrientetar** [unified-font-object/ufoLib#6]
This is particularly important on Windows, where we have to force LF line-endings (see the discussion on 0b60503f4f61ae04386ce1dd763af740b7232988) &ndash; for this reason, we open the files in binary mode.

**Comment by anthrotype** [comment]
if we use the `open` function from the `io` module instead of the python2 built-in `open` function, then we could control the newline character even when a file is open as text instead of binary. The `io.open` function in python3 is simply an alias to the python3 buillt-in `open`, so that using `io.open` all the time would make py23-sense.

```python
io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True)
```
https://docs.python.org/2/library/io.html#io.open

> On output, if newline is None, any '\n' characters written are translated to the system default line separator, os.linesep. If newline is '', no translation takes place. If newline is any of the other legal values, any '\n' characters written are translated to the given string.

Another advantage of `io.open` is the possibility to define an `encoding` to use for decoding bytes to unicodes (on read), or encoding unicodes to bytes (on write), whenever a file is open as text mode.
This is strictly related to https://github.com/unified-font-object/ufoLib/issues/5.

**Comment by adrientetar** [comment]
That sounds good.

**Comment by anthrotype** [comment]
we no longer use fontTools xmlWriter, and we always use LF when writing XML on all platforms.
