### ISSUE TITLE
[glifLib] caching raw GLIF data should be optional

### ISSUE THREAD

**Issue by justvanrossum** [unified-font-object/ufoLib#80]
I notice that for example `glyphSet.getUnicodes()` will cause _all_ raw GLIF data to be retained in memory. This is counter to what that method is for: to efficiently get all cmap info without the need to load all glyphs. 

In other words: this will use up a lot of memory for large glyph sets, and that's exactly the use case where you want to be conservative with memory.

**Comment by justvanrossum** [comment]
Was it ever measured how much this caching saves?

**Comment by typesupply** [comment]
> Was it ever measured how much this caching saves?

This was done a really long time (7 years!?) ago so I'm not 100% sure about the chronology of the implementation. From what I recall, I was solving a gnarly performance issue caused by glifLib repeatedly reading GLIF files. I *think* it had something to do with reading a UFO which triggered the unicodes to be read, the components to be mapped, the images to be mapped and other stuff. Then, the GLIF itself would be read. That was causing a severe performance problem in every use, so I switched to caching the raw text until parsing happened. I *probably* tested this, but I don't recall. I do remember having a script generated massive UFO that I used for unrealistic edge case testing back when I was working on this. But, I'm not 100% certain. It would probably be good to test this again if someone has time. There have been a lot of hardware I/O upgrades and ufoLib changes since then.

**Comment by justvanrossum** [comment]
The speedup may be significantly less on solid state drives.

I'll try to come up with a patch to optionally disable it. (Although I think it should actually be off by default.)

**Comment by anthrotype** [comment]
I see for fetching unicodes, image file names and component references, glifLib is still using an expat parser. For consistency we should use `ufoLib.etree` API for those, like we do for plists and for GLIF.
We could of use the elementtree "target" interface (jut like I did for [ufoLib.plistlib](https://github.com/unified-font-object/ufoLib/blob/5b85d8eaba4611abcbf7c9d22aff87f178098f65/Lib/ufoLib/plistlib.py#L137-L157)), which is supported by both cElementTree and lxml:
http://effbot.org/elementtree/elementtree-xmlparser.htm#the-target-interface

**Comment by anthrotype** [comment]
maybe we don't need to add a new option `useGlifCache=False` option. We can simply not attempt to load the requested glif from the `self._glifCache` whenever we are fetching unicodes (or image file names or component refs), but directly read off the `self.fs`.

**Comment by justvanrossum** [comment]
TBH, I'm not convinced ufoLib is the right place to do any kind of caching.

**Comment by anthrotype** [comment]
That’s a valid point. We can take the chance to drop that now that we are about to make this big move and consequent major version bump.

**Comment by typesupply** [comment]
I'm fine with this. It was an optimization from long ago that may no longer be needed.

**Comment by anthrotype** [comment]
ok, I'll remove it.
